### ISSUE TITLE
Using "include textmate::textmate2::beta" doesn't download or install anything.

### ISSUE THREAD

**Issue by charleshbaker** [boxen/puppet-textmate#5]
In my Puppetfile I have

```
github "textmate",     "1.1.0"
```

In my charleshbaker.pp I have

```
include textmate::textmate2::beta
```

But when I run scripts/boxen --no-fde textmate is not installed. Nor do I find the tarball.

```
cbaker1:our-boxen/ (master) $ find . -name "*.tbz"                                                                                                          [10:41:07]
cbaker1:our-boxen/ (master) $                                                                                                                               [10:41:16]
```

**Comment by charleshbaker** [comment]
If I hit the download URI, https://api.textmate.org/downloads/beta, the package does download.

**Comment by jacobbednarz** [comment]
This module has been deprecated in favour of [Boxen's inbuilt support for Homebrew/Caskroom](https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17).
